;;; typescript.el -*- lexical-binding: t; -*-

(require 'ob)
(require 'ob-typescript)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((typescript . t)))

(defun my/org-babel-execute:typescript (body params)
  "Execute a TypeScript BODY in Org Babel.

TypeScript is compiled directly from a temporary .ts file,
then the resulting JavaScript is executed with Node.js."
  (let* ((ts-file (org-babel-temp-file "babel-typescript-" ".ts"))
         (js-file (org-babel-temp-file "babel-typescript-" ".js"))
         (cmdline (or (cdr (assq :cmdline params)) ""))
         (tsc-command
          (format
           "npx -p typescript -- tsc --target ES2020 --module commonjs --outDir %s %s"
           (shell-quote-argument (file-name-directory js-file))
           cmdline)))

    ;; Write the Org Babel block to a temporary TypeScript file.
    (with-temp-file ts-file
      (insert body))

    ;; Compile the temporary TypeScript file.
    (let ((exit-code
           (process-file
            "sh"
            nil
            "*org-babel-typescript*"
            nil
            "-c"
            (format "%s %s"
                    tsc-command
                    (shell-quote-argument ts-file)))))

      (unless (zerop exit-code)
        (error "TypeScript compilation failed; see *org-babel-typescript*"))

      ;; Find the JS file generated by tsc.
      (let* ((generated-js
              (expand-file-name
               (concat (file-name-sans-extension
                        (file-name-nondirectory ts-file))
                       ".js")
               (file-name-directory js-file))))

        ;; Run the compiled JavaScript with Node.
        (org-babel-eval
         (format "node %s"
                 (shell-quote-argument generated-js))
         "")))))

(advice-add 'org-babel-execute:typescript
            :override
            #'my/org-babel-execute:typescript)
